"""Infrastructure constants for the THETA AI TRADER engine foundation."""

from typing import Final

ERROR_CODE_CONTEXT_INVALID: Final[str] = "ENGINE.BASE.CONTEXT.INVALID"
ERROR_CODE_CONTEXT_MISSING_FIELD: Final[str] = "ENGINE.BASE.CONTEXT.MISSING_FIELD"
ERROR_CODE_EXECUTION_UNHANDLED: Final[str] = "ENGINE.BASE.EXECUTION.UNHANDLED"
ERROR_CODE_RESULT_INVALID: Final[str] = "ENGINE.BASE.RESULT.INVALID"

DEFAULT_ENGINE_VERSION: Final[str] = "1.0.0"
