"""Strategy plugin contracts for THETA AI TRADER."""

from strategy.base_strategy import (
    STRATEGY_VERSION,
    BaseStrategy,
    ConfidenceBand,
    SignalAction,
    SignalConfidence,
    SignalDirection,
    StrategyContext,
    StrategyContextError,
    StrategyEngineConfigurationError,
    StrategyExecutionMode,
    StrategyFamily,
    StrategyMetadata,
    StrategyPluginConfig,
    StrategyRiskProfileHint,
    StrategySignalError,
    TradingSignal,
    confidence_band_for_score,
    validate_strategy_metadata,
    validate_strategy_plugin_config,
)

__all__ = [
    "STRATEGY_VERSION",
    "BaseStrategy",
    "ConfidenceBand",
    "SignalAction",
    "SignalConfidence",
    "SignalDirection",
    "StrategyContext",
    "StrategyContextError",
    "StrategyEngineConfigurationError",
    "StrategyExecutionMode",
    "StrategyFamily",
    "StrategyMetadata",
    "StrategyPluginConfig",
    "StrategyRiskProfileHint",
    "StrategySignalError",
    "TradingSignal",
    "confidence_band_for_score",
    "validate_strategy_metadata",
    "validate_strategy_plugin_config",
]
